FROM centos:7

MAINTAINER inocop

WORKDIR /tmp


# add nodejs8.x and passenger repository
RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash - \
&&  curl --fail -sSLo /etc/yum.repos.d/passenger.repo https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo


# yum install
RUN yum install -y sudo \
                   cronie \
                   which \
                   wget \
                   epel-release \
&&  yum install -y httpd \
                   httpd-devel \
                   mod_xsendfile \
                   mod_ssl \
                   mod_passenger-5.3.7-1.el7 \
                   libcurl-devel \
                   apr-devel \
                   apr-util-devel \
                   gcc-c++ \
                   make \
                   glibc-headers \
                   openssl-devel \
                   readline \
                   readline-devel \
                   libyaml-devel \
                   libxml2-devel \
                   libxslt-devel \
                   zlib \
                   zlib-devel \
                   sqlite-devel \
                   mysql \
                   mysql-devel \
                   git \
                   nodejs \
                   gettext \
                   ImageMagick \
&&  yum clean all


# ruby install
RUN wget http://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.gz \
&&  tar zxf ruby-2.5.3.tar.gz \
&&  cd ruby-2.5.3 \
&&  ./configure --disable-install-rdoc \
&&  make \
&&  make install \
&&  rm -rf /tmp/ruby-*


# global gem install
RUN bash -l -c 'gem install --no-document bundler  -v "1.17.2"' \
&&  bash -l -c 'gem install --no-document nokogiri -v "1.8.5"'


# apache disable PrivateTmp
RUN cp /usr/lib/systemd/system/httpd.service /etc/systemd/system/httpd.service \
&&  sed -i -e "s/PrivateTmp=true/PrivateTmp=false/g" /etc/systemd/system/httpd.service


# set TimeZone
RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
#RUN timedatectl set-timezone Asia/Tokyo  # build時にtimedatectlを実行できないので上の方法でタイムゾーンを変更。(コンテナ起動後にexecでなら可能)


# get build-arg
ARG RAILS_ENV

# set env for apache
RUN echo "RAILS_ENV=${RAILS_ENV}" >> /etc/sysconfig/httpd

# set conf for apache-passenger
ADD vhost.conf.tmp ./
RUN RAILS_ENV=${RAILS_ENV} cat vhost.conf.tmp | envsubst > /etc/httpd/conf.d/vhost.conf \
&&  rm -rf /etc/httpd/conf.d/passenger.conf   # mod_passengerインストール時に自動で作られる設定ファイルを削除


# install db tools for development
ADD install_adminer.sh ./
RUN if [ "${RAILS_ENV}" = "development" ] ; then ./install_adminer.sh ; fi


# chromium install

## epel-releaseからインストール
# RUN yum -y install chromium ipa-gothic-fonts ipa-mincho-fonts

# puppeteer経由でインストール
RUN yum -y install libX11 \
                   libXcomposite \
                   libXcursor \
                   libXdamage \
                   libXext \
                   libXi \
                   libXtst \
                   cups-libs \
                   libXScrnSaver \
                   libXrandr \
                   alsa-lib \
                   pango \
                   atk \
                   at-spi2-atk \
                   gtk3 \ 
                   # ja font \
                   ipa-gothic-fonts \
                   ipa-mincho-fonts \
&&  yum clean all

RUN npm install -g puppeteer@1.6.2 --unsafe-perm=true


# create user for passenger
RUN useradd -s /sbin/nologin railsdev \
&&  usermod  -u 1000 railsdev \
&&  groupmod -g 1000 railsdev


# delayed_jobのsystemd登録
ADD delayed_job.service.tmp ./
RUN RAILS_ENV=${RAILS_ENV} cat delayed_job.service.tmp | envsubst > /etc/systemd/system/delayed_job.service

# set use systemd
RUN systemctl enable httpd.service \
&&  systemctl enable crond.service \
&&  systemctl enable delayed_job.service \
# disable no need daemon \
&&  systemctl disable getty.target \
&&  systemctl disable systemd-udevd.service \
&&  rm -f /lib/systemd/system/systemd*udev* \
&&  rm -f /lib/systemd/system/getty.target


CMD /sbin/init
WORKDIR /var/www/app
